# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='escolhido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='comum.Perfil'),
        ),
    ]
