# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20180129_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='curtida',
        ),
        migrations.AddField(
            model_name='job',
            name='curtida',
            field=models.ManyToManyField(blank=True, null=True, related_name='curtidas', to='comum.Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gitHub',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='experiencia',
            field=models.TextField(blank=True, help_text='Projetos feitos', null=True, verbose_name='Experiencia'),
        ),
    ]
