# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_auto_20180130_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='comum.Perfil'),
        ),
        migrations.AlterField(
            model_name='job',
            name='descricao',
            field=models.TextField(help_text='Fale detalhes do serviço pretendido.', verbose_name='Descrição'),
        ),
    ]
