# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_auto_20180130_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='curtida',
        ),
        migrations.AddField(
            model_name='perfil',
            name='curtida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='comum.Perfil'),
        ),
    ]
