# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_auto_20180130_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curtida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='comum.Job'),
        ),
    ]
