# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_auto_20180130_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ('criado_em',), 'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descricao',
            field=models.CharField(max_length=512, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('producao', 'Producão'), ('finalizado', 'Finalizado'), ('reaberto', 'Reaberto'), ('em_analise', 'Em ana  lise')], default='aberto', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='comum.Endereco'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil_profissional',
            field=models.TextField(help_text='Formação, Cursos extras', verbose_name='Perfil profissional'),
        ),
    ]
