# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0009_auto_20180222_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='titulo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='comum.Endereco'),
        ),
    ]
