# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0010_auto_20180227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.CharField(max_length=20, verbose_name='Data de nascimento'),
        ),
    ]
