# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0010_auto_20180227_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('participantes', models.ManyToManyField(related_name='chats', to='comum.Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('lida', 'Lida')], default='enviada', max_length=64, verbose_name='Status')),
                ('texto', models.CharField(max_length=256, verbose_name='Texto')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.Chat')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_mensagens', to='comum.Perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
